services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    networks:
    - infra-net
    ports:
    - 6379:6379
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy noeviction
    volumes:
    - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    healthcheck:
      test:
      - CMD
      - redis-cli
      - ping
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
volumes:
  redis-data: null
networks:
  infra-net:
    external: true