services:
  watchtower:
    image: nickfedor/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    networks:
    - infra-net
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - DOCKER_API_VERSION=1.46
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
networks:
  infra-net:
    external: true