version: '3.8'
services:
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
    - 53:53/tcp
    - 53:53/udp
    - 3001:3000/tcp
    - 8082:80/tcp
    - 853:853/tcp
    - 5443:5443/tcp
    volumes:
    - <host-path>
    - <host-path>
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    healthcheck:
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://localhost:53/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s