version: '3.8'
services:
  hbbs:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbs
    restart: unless-stopped
    command: hbbs -r 192.168.0.0
    ports:
    - 21116:21116/tcp
    - 21116:21116/udp
    volumes:
    - <host-path>
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    logging: &id001
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    healthcheck:
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://localhost:21116/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
  hbbr:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-hbbr
    restart: unless-stopped
    command: hbbr
    ports:
    - 21117:21117/tcp
    volumes:
    - <host-path>
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
    logging: *id001
    healthcheck:
      test:
      - CMD-SHELL
      - wget --no-verbose --tries=1 --spider http://localhost:21117/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s